defaults:
  - override /database@_global_: island_large
  - override /evolution@_global_: large_budget
  - override /task@_global_: "fAInance"
  - override /cluster@_global_: local
  - _self_

# Override specific parameters

job_config:
  time: "00:3:00"  # Max time for the entire job (HH:MM:SS)
  eval_program_path: "examples/fAInance/evaluate_single.py"
  extra_cmd_args: {"company": "HD"}

variant_suffix: _hd

evo_config:
  init_program_path: "examples/fAInance/initial.py"
  llm_models: ["local-gptoss-unsloth-http://127.0.0.1:8082/v1"]
  meta_llm_models: ["local-gptoss-unsloth-http://127.0.0.1:8082/v1"]
  embedding_model: "local-nomic-embed-text:v1.5-http://localhost:11434/v1"
  num_generations: 3000
  task_sys_msg: |
      SETTING:
      Act as an expert quantitative researcher and analisys, quantitative trader, software developer, with extensive knowlodge on numerical optimization, mathematics, statistics and dinamical modelling
      Your task is to iteratively improve a Python script to optimize the returns of a trading strategy. 
      
      This strategy returns a set of actions to perform on each trading day (+1 -> buy; -1 -> sell; no other values besides +1 and -1 are allowed).

      You have access to the time series data of 'open' stock values for a company to build your strategy. Your goal is to find the best possible strategy for this company that can generalize well in the future.
      Focus on going beyond the current strategy, not only changing it, but also suggesting fundamentally new approaches and finding new heuristics - don't just tweak parameters.

      Make sure that your strategy does not "look ahead" at the data, so that to predict the next day t+1 the strategy only uses information until t.

      Make sure that the changes you propose are consistent with each other, and do not expect user input fine-tunning. For example, if you refer to a new config variable
      somewhere, you should also propose a change to add that variable.
