defaults:
  - override /database@_global_: island_large
  - override /evolution@_global_: large_budget
  - override /task@_global_: circle_packing
  - override /cluster@_global_: local
  - _self_


# Override specific parameters

variant_suffix: "_gptoss120b_guadiana"

evo_config:
  llm_models: ["local-gptoss-unsloth-http://127.0.0.1:8080/v1"]
  meta_llm_models: ["local-gptoss-unsloth-http://127.0.0.1:8080/v1"]
  embedding_model: "local-nomic-embed-text:v1.5-http://localhost:11434/v1"
  results_dir: results/shinka_circle_packing/2025.10.13152106_gptoss120b_guadiana
  num_generations: 500